export default {
    discountTitle:'EARN 50 TICKETS FOR EVERY FRIEND WHO JOIN & CONNECT A DEBIT/CREDIT CARD TO REBATUS',
    authtoken:'',
    regData : {},
    userData : {},
    profileDetailsData : {},
    paymentData : {},
    email : '',
    deviceToken:'',
    pushPermission:null,
    profileUpdated : false,
    selectedStartdate:{},
    selectedType:null,
    selecteddata:'',
    selectedActive:'',
    selectedEnddate:{},
    selectedDate:{},
    moneyMattersPostData:null,
    selectedCurrency:null,
    selectedLanguage:null,
    isLoad:true,
    apiCall:null,
    packageNamae:null,
    Register:null,
    Login:null,
    Home:null,
    Gender:null,
    Month:null,
    Money_Matter:null,
    Offer:null,
    Profile:null,
    Rebates:null,
    Tickets:null,
    Banks:null,
    menuIndex:0,
    selectedbank:0,
    selectedbankid:0,
    moneyOutData:{},
    moneyInData:{},
    moneyInPostData:{},
    moneyOutPostData:{},
    moneyVsOutData:{},
    isNavigate:false,
    shareNavigate:false,
    shareData:'',
    planData:null,
    isNavigateToLogin:false,
    isNavigateToBank:false

}